### ISSUE TITLE
How do you switch between the integrated and discrete graphics?

### ISSUE THREAD

**Issue by svaxy** [sudeepn/Lenvyx#4]
Did you manage to get the switchable graphics work 100%? I'm trying to get the ATI/AMD Radeon card working to be able to connect an external display, but didn't have any luck.

Using Ubuntu 14.04

**Comment by jarthod** [comment]
I managed to get it working using vga_switcheroo **before** 14.04 but I'm not sure for 14.04.
I ended up just wanting to disable the ATI card for battery life, I almost never tried to use it.
Have you tried the commands in `switchable-graphics.conf` ? there is one commented to switch to discrete graphics, it should be something like (as root):

```bash
# Turn ON the unused card to ensure we can switch
echo ON > /sys/kernel/debug/vgaswitcheroo/switch

# Switch to the integrated graphics (low power)
# echo DIGD > /sys/kernel/debug/vgaswitcheroo/switch

# Switch to the Discrete Graphics (high power)
echo DDIS > /sys/kernel/debug/vgaswitcheroo/switch

# Turn OFF the unused card to save power
echo OFF > /sys/kernel/debug/vgaswitcheroo/switch
```

You can always use `sudo cat /sys/kernel/debug/vgaswitcheroo/switch` to know current status.
